- .eslintrc.cjs
- environments/.env.development
- environments/.env.production
- package.json
- src/hooks/useCreatePost.js
- src/hooks/useFishData.js
- src/hooks/useFishInfo.js
- src/hooks/useFishTypes.js
- src/hooks/useUpdatePost.js
- src/hooks/useUserData.js
- src/index.jsx
- src/mock/jsonplaceholder/posts.js
- src/pages/Example.jsx
- src/utils/fetcher.js
- src/utils/mockFetcher.js
- tailwind.config.js
- vite.config.js
1. post & put sample code https://github.com/sky172839465/cwa-shop/pull/2/commits/bc0af13f88aa73e7168a1e13eb6033e115c3ceb3
1. demo page `/example`
> feat: add post & put example

- .eslintrc.cjs
- package-lock.json
- package.json
- src/components/Dropzone/accept.js
- src/components/Dropzone/index.jsx
- src/components/NavBar/index.jsx
- src/pages/Product.jsx
- 增加新增商品 UI
- 圖片限制 jpg png
- 影片限制 mp4
- 從 nabar product icon 進入頁面 `/product`
- demo
> feat: add upload product UI

- src/components/Dropzone/index.jsx
- src/components/NavBar/index.jsx
- src/pages/Product.jsx
- src/utils/getFormValues.js
- get formValues on submit
- demo
> feat: get form values with fileList

- src/components/Dropzone/index.jsx
- src/utils/getFormValues.js
1. save upload file from file object to base64 data
1. demo
> feat: upload file save as base64 data

- package-lock.json
- package.json
- src/components/Dropzone/index.jsx
- src/components/Form/FocusError.jsx
- src/components/Form/FormRow.jsx
- src/sites/internal/pages/index.jsx
- src/utils/getFormValues.js
1. field validation (images & videos needs one not empty)
1. file limit `6 MB`
1. submit field error will redirect to field
<video src="https://github.com/sky172839465/cwa-shop/assets/9082423/fbdc7eb2-5f38-4ad4-9cb7-2a0acd5d49e5" />
> feat: add form validation

- .eslintrc.js
- src/components/Card/index.jsx
- src/components/Model/Product/index.jsx
- src/components/Router/getRoutes.js
- src/components/Router/index.jsx
- src/mock/battaFish/fish.js
- src/sites/external/index.jsx
- src/sites/external/pages/confirm/index.jsx
- src/sites/external/pages/index.jsx
- src/sites/login/pages/index.jsx
- src/state/selectedProducts.js
1. load data before site route to page
1. default select product from api
1. check reserve on select
1. update login page style
1. update image gallary data structure
> feat: add site loader

- package-lock.json
- package.json
- src/components/Drawer/index.jsx
- src/components/Model/Product/index.jsx
- src/components/Video/index.jsx
- src/mock/battaFish/fish.js
- src/sites/example/index.html
- src/sites/external/index.html
- src/sites/external/pages/complete/index.jsx
- src/sites/external/pages/confirm/index.jsx
- src/sites/external/pages/index.jsx
- src/sites/index.html
- src/sites/internal/index.html
- src/sites/login/index.html
- src/state/orderData.js
1. UI add preorder & order api
1. add complete page
1. refactor image gallery
1. image gallery support video
> feat: add api order & update gallery style

- src/components/CartBottomItems/index.jsx
- src/components/LazyImage/index.jsx
- src/components/Model/Product/index.jsx
- src/components/Video/index.jsx
- src/sites/external/pages/confirm/index.jsx
- src/sites/external/pages/index.jsx
1. fix total price in product page incorrect
1. fix total price, price, and currency in confirm incorrect
1. fix product submit to confirm page selected products incorrect
1. fix when image slide with video, image can't vertical center
1. fix slide switch sometime broke the page by stop video instance
> fix: issue in meeting

- src/components/Dropzone/index.jsx
- src/components/Model/Product/index.jsx
1. change maximum load size
1. fix silder image url incorrect
> fix: large image url incorrect & change maximum load size

- src/components/CartBottomItems/index.jsx
- src/components/CartItems/index.jsx
- src/components/Dropzone/index.jsx
- src/components/NavBar/index.jsx
- src/locales/en/translation.json
- src/locales/jp/translation.json
- src/locales/zh-TW/translation.json
- src/sites/external/pages/confirm/index.jsx
左上角的「CWA商品」改成「鬥魚訂單系統」、「Betta Purchase System」、「ベタ購入システム」 "頁面詞句翻譯：
Cart is empty = 購物車（0） = カート（0）
Total count 改成 Total piece = 數量 = 合計個数
Total price 改成 Total amount = 金額 = 合計金額
CONFIRM ORDER = 商品確認 = 商品確認"
"Image = 影像 = 画像
FishType Name 改成 Common Name = 品名 = 生物名
ItemSerial 改成 Number = 編號 = 番号
ItemPrice 改成 Amount = 金額 = 総金額
Total selected 改成 Total piece = 數量 = 合計個数
Fish types 改成 List = 購買清單 = 購入リスト
Total price 改成 Total amount = 總金額 = 合計金額
SUBMIT CART = 訂單確認 = 注文内容確認
REMOVE ALL = 全部刪除 = オールクリア"
> 進行中英日語細調整：

- src/sites/index.jsx
1. fix https://github.com/sky172839465/cwa-shop/pull/125
> fix: spa mode miss root ignore isAuthRoutes

- src/hooks/useRecognition.js
- src/sites/demo/pages/batch/Table.jsx
- src/sites/demo/pages/batch/TableRow.jsx
- src/utils/retry.js
1. fishType should show name
1. show fishType name with fishType id
1. update recognition message by status
1. skeleton with larger size
> fix: fishType should show name

- src/sites/demo/pages/batch/TableRow.jsx
> chore: change recognize message & icon

- package-lock.json
- package.json
- src/hooks/useQueue.js
- src/hooks/useRecognition.js
- src/hooks/useUploadS3.js
- src/sites/demo/pages/batch/Table.jsx
- src/sites/demo/pages/batch/TableRow.jsx
1. chrome maximum request size 6, keep s3 queue in 5 request, so other request won't be pending
> feat: add p-queue control maximum s3 request count

- src/hooks/useRecognition.js
- src/sites/demo/pages/batch/EditModal.jsx
- src/sites/demo/pages/batch/Table.jsx
- src/sites/demo/pages/batch/TableRow.jsx
- src/sites/demo/pages/batch/index.jsx
1. recognition failed allow user update data to mark as uploaded
<video src="https://github.com/sky172839465/cwa-shop/assets/9082423/61a4cf10-becd-4690-8d7d-f449b288e5fd" />
1. update validation if fishType keep -1 check as empty field
> feat: recognition failed allow user update data to mark as uploaded

- src/hooks/useRecognition.js
- src/mock/battaFish/upload.js
- src/sites/demo/pages/batch/EditModal.jsx
- src/sites/demo/pages/batch/TableRow.jsx
- src/sites/demo/pages/batch/index.jsx
1. edit status editable & filled modal fields
1. after edit success, error icon will become success
> feat: add upload status edit show error but fill fields and editable

- src/mock/battaFish/upload.js
- src/sites/demo/pages/batch/EditModal.jsx
1. edit modal add originItemImage collapse under video
> feat: edit modal add originItemImage

- src/components/Drawer/index.jsx
- src/components/NavBar/LangsAction/index.jsx
- src/components/NavBar/Logo/index.jsx
- src/components/NavBar/LogoutAction/index.jsx
- src/components/NavBar/OrderAction/index.jsx
- src/components/NavBar/UserAction/index.jsx
- src/components/NavBar/index.jsx
- src/components/Router/index.jsx
- src/sites/order-domestic/index.html
- src/sites/order-domestic/index.jsx
- src/sites/order-domestic/pages/index.jsx
- src/sites/order-export/index.html
- src/sites/order-export/index.jsx
- src/sites/order-export/pages/index.jsx
- vite.config.mjs
1. add order page with mock UI
1. split nav bar action to multiple component for different sites usage
> add order page

- src/sites/purchase-domestic/pages/index.jsx
<video src="https://github.com/sky172839465/cwa-shop/assets/9082423/26766c52-dab1-4e7e-99fd-3b613905e920" />
> Add table action tip & sticky table 

- src/sites/purchase-domestic/pages/index.jsx
ref: https://github.com/sky172839465/cwa-shop/pull/169
> style: fix sticky header position incorrect

- src/components/NavBar/index.jsx
- src/sites/purchase-domestic/pages/index.jsx
1. update table height
1. fix nav bar action incorrect
> style: update table height

- environments/.env.development
- environments/.env.mock
- environments/.env.production
- src/components/NavBar/LogoutAction/index.jsx
- src/components/NavBar/index.jsx
- src/components/Portal/WithLinks/index.jsx
- src/components/Router/getAuth.js
- src/components/Router/getRoutes.js
- src/sites/external-demo/index.html
- src/sites/external-demo/index.jsx
- src/sites/external/pages/index.loader.js
- src/utils/clearExpiredLoginToken.js
- src/utils/getLoginLogoutUrl.js
1. 可自訂全部網站登入登出連結
1. 複製 external 網站，external-demo 可以獨立部署與另外訂登入登出
1. external & external-demo 在 35 分鐘後清除登入 token
> Allow custom login/logout, mirror external

- src/sites/purchase-domestic/pages/CountSelect.jsx
- src/sites/purchase-domestic/pages/confirm/index.jsx
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> feat: add purchase confirm page

- src/sites/purchase-domestic/pages/index.jsx
<video src="https://github.com/sky172839465/cwa-shop/assets/9082423/e7c47244-36b5-4324-ac39-c18d9c76539f" />
> feat: allow filter by api or client filter

- src/sites/purchase-domestic/pages/index.jsx
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> feat: change mobile UI for larger search input

- src/components/Modal/Purchase/index.jsx
- src/components/SearchMenu/constants.js
- src/components/SearchMenu/index.jsx
- src/components/SearchMenu/useSearchMenuAction.js
- src/hooks/useCategoryInfo.js
- src/hooks/useExportCategoryInfo.js
- src/hooks/useExportGetCategoryList.js
- src/hooks/useExportQueryInfo.js
- src/hooks/useFishData.js
- src/hooks/useFishTypes.js
- src/hooks/useGetCategoryList.js
- src/hooks/useQueryInfo.js
- src/mock/purchase/category.js
- src/sites/purchase-domestic/pages/index.jsx
1. with mock api
1. client filter
1. add modal content
> purchase page with mock api

- src/components/Modal/Purchase/index.jsx
- src/sites/purchase-domestic/pages/PurchaseModalTable.jsx
- src/sites/purchase-domestic/pages/PurchaseTable.jsx
- src/sites/purchase-domestic/pages/constants.js
- src/sites/purchase-domestic/pages/index.jsx
> feat: add to cart show result on table

- src/components/SearchMenu/index.jsx
- src/mock/purchase/category.js
- src/sites/purchase-domestic/pages/PurchaseTable.jsx
- src/sites/purchase-domestic/pages/ViewFileModal.jsx
- chore: disable ai search
- add view file modal
> feat: add view file modal

- src/sites/purchase-internal/pages/demand-order/index.jsx
- src/sites/purchase-internal/pages/index.jsx
- src/sites/purchase-internal/pages/quotation/index.jsx
> add demand-order page & root purchase-internal endpoint

- src/mock/purchase/order.js
-----
<a href="https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/fix-error"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/fix-error)._
> fix: destructure property 'order_items' error

- src/utils/mockFetcher.js
-----
<a href="https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/mock-api"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/mock-api)._
> fix: mock api get method also need filter

- src/sites/purchase-domestic/pages/confirm/index.jsx
-----
<a href="https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/confirm-flow"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/confirm-flow)._
> chore: update remove flow

- package-lock.json
- package.json
- src/components/CartBottomItems/index.jsx
- src/components/Drawer/index.jsx
- src/mock/purchase/order.js
- src/sites/purchase-domestic/pages/CustomCartBottomItems.jsx
- src/sites/purchase-domestic/pages/index.jsx
-----
<a href="https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/sky172839465/patch-3880"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/sky172839465/patch-3880)._
> style: refactor drawer

- src/components/SearchMenu/index.jsx
-----
<a href="https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/patch13"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/sky172839465/cwa-shop/tree/patch13)._
> fix: close search type notworking
